### ISSUE TITLE
Is it possible to store an object in a model attribute?

### ISSUE THREAD

**Issue by matthewnessworthy** [toranb/ember-cli-simple-store#22] opened 2015-09-29 19:31 UTC
Currently, there is no dirty checking or triggers to the observer when changing simple object properties. Is there any plans to add support for this use-case?

**Comment by toranb** [comment] 2015-09-29 19:52
Maybe you could tell me a little more about your requirement :)

I'm actually curious to see how other people use this library and if you use case is simply

my model has property name and when name changes/or is dirty I'd like to know (or another CP might).

If this isn't your scenario ... would you mind going into a little more detail when you have time?

**Comment by matthewnessworthy** [comment] 2015-09-29 21:50
Sure, I'll give a slightly simplified version. 
I'm currently working on a tree structure of nodes (files/folder), each node contains an object called nodeInfo, which contains a a list of properties and possibly other embedded objects depending on its type.
I don't need the whole polymorphic behaviour as in ember-data, simple objects are fine for me as I'm wrapping a lot of the functionality in components/helpers instead of the base models.

```
// models/node.js
import Ember from 'ember';
import { attr, Model } from 'ember-cli-simple-store/model';

export default Model.extend({
    parent: attr(),
    hasChildren: attr(false),
    nodeInfo: attr({}),
    alias: attr(Ember.A()),
});
```

`nodeInfo` can contain an object similar to

```
{
    type: 'folder', // or file
    name: '/',
    isHidden: false,
    isReadonly: false,
    //etc
}
```

```
// some component

    isModified: Ember.computed('model.isDirty', function() {
        return this.get('model.isDirty');
    }),
```

`isModified` will return true if any of the attributes except for `nodeInfo` is modified

_Edit_
values in the attr `nodeInfo` which are changed are reflected correctly and update the UI as expected

**Comment by toranb** [comment] 2015-09-30 00:54
Huh this is similar to what I use the the addon for day-to-day but I usually create another object/model and link the two. Would this be an option for you? 

In your example you'd create a new model/ember object called node (or whatever you feel is valid).

Next in the model you show at the top, inject the store and write up a computed property to return the related node (if you need /want detail on injecting this ping me w/ more details -I'm yet to release anything public on this pattern and it might be unclear).

This approach gives you all the dirty tracking you need because you literally end up w/ another first-class object that has attrs for type, name, isHidden, isReadonly (and you could easily ask if any of those attr properties are dirty by looking at the ember object).

Is this an option/appealing in anyway? I do this today for one-to-many and m2m relationships (similar to your setup in some ways)

**Comment by matthewnessworthy** [comment] 2015-09-30 06:33
That sounds like it would be a pretty good fit, it would be great if you could share some examples of this approach so I can see how well it would integrate with my use-case. 

In this approach, how do you handle the serialisation of the linked models when preparing to send an update to the api, or, when the linked model has no primary/parent id due to it being something like a [model fragment](https://github.com/lytics/ember-data.model-fragments)?

**Comment by toranb** [comment] 2015-10-01 01:11
Here is the quick rundown of what this might look like

1) if you don't already have a simple inject helper in your app -add this little guy (requires ember-cli-injection addon)

https://github.com/toranb/ember-2-skeleton-app/blob/master/app/utilities/inject.js

2) in the top level model inject the store and create a computed that can "lookup" the related object

``` js
export default Model.extend({
    store: inject('main'),
    node: Ember.computed('belongs_to.firstObject'),
    belongs_to: Ember.computed(function() {
      let store = this.get('store');
      let filter = function(node) {
        let user_ids = node.get('users') || [];
        return Ember.$.inArray(this.get('id'), user_ids) > -1;
      };
      return store.find('node', filter.bind(this), ['users']);
    })
});
```

3) next in your "node" model you should maintain a "users" array (or whatever the plural of the related model is). 

``` js
var NodeModel = Model.extend({
    name: attr(),
    users: attr([])
});
```

4) some other object in your app (on boot, or a deserializer after some ajax call) you need to setup the "users" array by pushing a related id into the array as you create each node/user

This example shows how I often do a one to many (a user in this example can have exactly one node, but a node can "belong_to" many users). If your object graph isn't like this you might alter it but it's a fairly simple example that should provide the missing link

Let me know if you need more help/ this isn't clear/ this won't work/etc. I'll leave the issue open until you feel good about it /want to close it out :)

**Comment by matthewnessworthy** [comment] 2015-10-02 06:35
Thanks for the code example and hints, I'll give it a shot shortly and let you know how it turns out.
Much appreciated.

**Comment by matthewnessworthy** [comment] 2015-10-12 21:09
@toranb This works perfectly, thanks.
I'm running into a separate unrelated issue at the moment relating to adding items to the store. When there are a few thousand records in the store the time to push a record increases significantly, from ±1ms with a few records up to 11sec (per push) when there are about 4000 records.
I've tried to mitigate this by wrapping bulk data pushes with `store.beginPropertyChanges();` and `store.endPropertyChanges();` which makes a huge difference, but I'm still running into issues when the store gets larger.

**Comment by toranb** [comment] 2015-10-13 14:13
@matthewnessworthy wow the performance issue seems a little concerning. I'd need some time to learn enough about large data set perf in JS to diagnose this issue (not sure if it's purely that it "looks slow" -ie: we could make the push async instead of sync ... or if it's truly a limitation of my dual push (as I keep track of the object in 2 data structures and both get "pushed into" sync during that single operation).

Would you have anything I could start with later this week/early next that shows this off? Or can I simply loop 4000x doing push and then "watch the next slow push happen" ?

Also is this slow on desktop devices/mobile devices? Any other context about how and when you see this?

**Comment by matthewnessworthy** [comment] 2015-10-13 14:57
Let me throw together a little something this evening and see under which min/max limits things start to slow down

**Comment by matthewnessworthy** [comment] 2015-10-13 16:34
@toranb take a peek at https://github.com/matthewnessworthy/ember-cli-simple-store-perf
Start the ember server and go to http://localhost:4200/store from there you can add 100 with or without property change grouping.
In console I'm simply outputting the total time per 100 records

**Comment by matthewnessworthy** [comment] 2015-10-13 22:07
You may wish to consider including a `pushMany` function in the store and wrap it with `beginPropertyChanges()` and `endPropertyChanges()` as I've found that it provides a considerable speed improvement.
As for the speed decrease when pushing records to the store, I believe it relates to the observers/computed properties firing on the source array when changes are propagated.

**Comment by toranb** [comment] 2015-10-15 01:14
@matthewnessworthy great work on this! I'll give this a look the next few days to see what I can learn/ if I can improve it (with or/ without the pushMany as you mention)

**Comment by toranb** [comment] 2015-10-15 01:20
Quick update -removing this second "push" (for the array side of the store) kept the pushes blazing fast 

https://github.com/toranb/ember-cli-simple-store/blob/master/addon/store.js#L12

If we remove this the array find like funcs wouldn't be "as easy" to implement so I'll need to do some research.

**Comment by toranb** [comment] 2015-10-19 04:48
**Status update for the weekend**

I've found that only using a hash has a limitation when I create the CP that transforms the cached data into an ArrayProxy. If I "ask" for the findAll using a getter it will return the correct thing after a push, but today any array returned is simply up to date w/out asking. 

The root of the problem is that I don't (yet) know how to break the CP's  cache to have the ArrayProxy content property re-evaulated when a new key is added (a large part of the problem is that the hash doesn't have a "name" or key for the id that gets pushed in for a given type). Instead of id: 1 the hash has a key of 1, 2, or whatever UUID value the user adds.

``` js
    _findAll: function(type) {
        var self = this;
        var all = identityMapForType(type, this);
        var args = Ember.keys(all).map(function(key) {
            return "source." + key;
        });
        return Ember.ArrayProxy.extend({
          content: Ember.computed(function () {
            var everything = [];
            var theMap = this.get("source");
            for(var item in theMap){
                everything.push(theMap[item]);
            }
            return Ember.A(everything);
          }).property()
        }).create({
          source: all
        });
    }
```

**Comment by toranb** [comment] 2015-10-23 15:03
@matthewnessworthy I spent a few nights this week looking for a solution to my ArrayProxy from hash problem but so far I still can't get a computed to re-fire (for the underlying array I create on the fly using only a single hash). I learned a fair amount trying to make this hack work but with limited bandwidth I want to back up and look at the raw perf problem with doing a push into the array part of the store (the original problem I found when you wrote me about this).

I'll put some time in this weekend to better understand the root cause (sorry for the slow progress on this).

**Comment by matthewnessworthy** [comment] 2015-10-23 15:06
Thanks for spending your time on this, I hope you get an eureka moment.

**Comment by toranb** [comment] 2015-10-23 15:19
Lets close this out and open a new ticket about perf - specifically about the issues you are having :)

**Closed as completed by toranb** 2015-10-23 15:19 UTC

**Comment by matthewnessworthy** [comment] 2015-10-23 15:41
:+1: sounds like a plan

**Comment by toranb** [comment] 2015-10-23 18:32
I opened issue #25 to move the perf discussion along. @matthewnessworthy I asked for a clarification to get us off on the right foot this time :)
